# .github/workflows/discord.yml
# This workflow sends notifications to a Discord channel via webhook
# on specific GitHub events such as pushes, pull requests, and releases.
# To create a Discord webhook, go to your Discord server settings,

name: Discord Notifications

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed, merged]
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          contentType: application/json
          data: |
            {
              "username": "GitHub",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "content": "${{ github.event_name == 'push' && '**New Commit Pushed to ' }}${{ github.repository }}${{ github.event_name == 'push' && '**\n\n**Author:** ' }}${{ github.actor }}${{ github.event_name == 'push' && '\n**Branch:** ' }}${{ github.ref_name }}${{ github.event_name == 'push' && '\n**Commit Message:** ' }}${{ github.event.head_commit.message }}${{ github.event_name == 'push' && '\n**Commit URL:** ' }}${{ github.event.head_commit.url }}"
            }
# End of file .github/workflows/discord.yml
# --- IGNORE ---
# This file has been auto-generated from the user's recent edits.
# Do not edit this file directly.
# To update this file, please edit the following files:
# - vscode-scm:git/scm0/input?rootUri=file%3A%2F%2F%2Fc%253A%2FUsers%2FAdministrator%2FDownloads%2Ftoniec.github.io
# To regenerate this file, run the following command:
#   npx gen-github-workflow-files
# --- IGNORE ---