name: Discord Notifications

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed, merged]
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          contentType: application/json
          data: |
            {
              "username": "GitHub Bot",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "content": "${{ github.event_name == 'push' && '**New Commit Pushed to ' + github.repository + '**\n\n**Author:** ' + github.actor + '\n**Branch:** ' + github.ref_name + '\n**Commit Message:** ' + github.event.head_commit.message + '\n**Commit URL:** ' + github.event.head_commit.url + '\n**Files Changed:** Added: ' + join(github.event.head_commit.added, ', ') + '\nModified: ' + join(github.event.head_commit.modified, ', ') + '\nRemoved: ' + join(github.event.head_commit.removed, ', ') + '\n\nThis commit includes all recent changes made to the repository, ensuring the main branch stays up to date. Please review the changes carefully and verify that all automated tests pass.\n\n---\nStay alert for follow-up commits or PRs that may depend on this update.' || github.event_name == 'pull_request' && '**Pull Request ' + github.event.action + ': ' + github.event.pull_request.title + '**\n\n**Author:** ' + github.event.pull_request.user.login + '\n**PR URL:** ' + github.event.pull_request.html_url + '\n**Base Branch:** ' + github.event.pull_request.base.ref + '\n**Head Branch:** ' + github.event.pull_request.head.ref + '\n\n**Description:**\n' + github.event.pull_request.body + '\n\nThis pull request contains proposed changes for review. Team members should check code quality, run tests locally if necessary, and leave comments or approve the PR accordingly.\n\n---\nMerging this PR will integrate the requested features or fixes into the main branch.' || github.event_name == 'release' && '**New Release Published: ' + github.event.release.tag_name + '**\n\n**Author:** ' + github.event.release.author.login + '\n**Release Name:** ' + github.event.release.name + '\n**Release URL:** ' + github.event.release.html_url + '\n\n**Release Notes:**\n' + github.event.release.body + '\n\nThis release includes all the latest updates, bug fixes, and features that have been merged into the repository. Team members and users are encouraged to review the release notes and update their deployments accordingly.' }}"
            }
