name: Discord Notifications

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed, merged]
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          contentType: application/json
          data: |
            {
              "username": "GitHub Bot",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "content": "${{ github.event_name == 'push' && '**New Commit Pushed to ' }}${{ github.repository }}${{ github.event_name == 'push' && '**\n\n**Author:** ' }}${{ github.actor }}${{ github.event_name == 'push' && '\n**Branch:** ' }}${{ github.ref_name }}${{ github.event_name == 'push' && '\n**Commit Message:** ' }}${{ github.event.head_commit.message }}${{ github.event_name == 'push' && '\n**Commit URL:** ' }}${{ github.event.head_commit.url }}"
            }
